<?php

namespace App\Infrastructure\Cart\Coupon\Validation;

use App\Models\Coupon;
use Exception;

class CheckUsage extends AbstractHandler
{
  /**
   * @throws Exception
   */
  public function handle(?Coupon $coupon): Coupon|null
  {
    $max = $coupon->max_use;
    $usage = $coupon->usage;
    $remaind = $max - $usage;

    if ($remaind <= 0) {
      throw new Exception("سقف اعتبار این کوپن به پایان رسیده است");
    }


    return parent::handle($coupon); // TODO: Change the autogenerated stub
  }
}
